apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-admin-rolebinding
  namespace: team-c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: team-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: team-c-admin@mydomain.com
